
discord:
  webhook_url: #ここに発行されたdiscordwebhookのurlを添付してください。


notifier:
  threshold: #ここに設定したいメールの基準スコアを入力してください。
  max_check: 

scoring:

  keywords: #ここに、重要ワードとして登録したい単語を入力してください。


#以上、全ての入力方法は、README.mdの「yamlファイルの編集方法」を参照してください。


